name: Packages Split
on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  packages_split:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - local_path: 'Components/Http'
            repository: 'munastack-http'
          - local_path: 'Components/Routing'
            repository: 'munastack-routing'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Split and Push
        uses: symplify/monorepo-split-github-action@main
        env:
          PAT: ${{ secrets.PAT_TOKEN }}
        with:
          package_directory: ${{ matrix.package.local_path }}
          repository_organization: 'sinnerII'
          repository_name: ${{ matrix.package.repository }}
          branch: main
          user_name: "sinnerII"
          user_email: "bsdamulet@gmail.com"
          tag: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
