name: Packages Split

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  packages_split:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - local_path: 'src/Components/Http'
            repository: 'munastack-http'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a /tmp/ssh_agent.sock > /dev/null
          ssh-add - <<< "${{ secrets.MUNA }}"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Split and Push
        uses: symplify/monorepo-split-github-action@main
        with:
          package_directory: ${{ matrix.package.local_path }}
          package_repository: 'git@github.com:sinnerII/${{ matrix.package.repository }}.git'
          branch: main
          user_name: "sinnerII"
          user_email: "bsdamulet@gmail.com"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
